### PR TITLE
fix(deps): install python3-venv module

### PR DESCRIPTION
**Pull request by epiccurious**

### CODE REVIEW

**Comment by epiccurious** [comment]
Tested on Proxmox VMs running Ubuntu 24, 22, and 20. MR is ready for review.

**Comment by epiccurious** [comment]
Squashed commits.

**Comment by JWWeatherman** [comment]
PR accepted but it a duplicate of another pending PR.

**Comment by epiccurious** [comment]
@JWWeatherman can you please link to the PR this fix duplicates?

**Pull request closed without merging**
